### ISSUE TITLE
Cannot read property 'component' of undefined on Vue

### ISSUE THREAD

**Issue by romain-granai** [owliehq/vue-addtohomescreen#7]
Hi, I've installed the plugin to my vue js app (Vue 3), then in my main.js : 

`import VueAddtohomescreen from '@owliehq/vue-addtohomescreen';`
`app.use(VueAddtohomescreen);`

and then used the component somewhere 

`<add-to-homescreen />`

But there is an error, how could I fix this?

```
index.js?bc58:14 Uncaught TypeError: Cannot read property 'component' of undefined
    at Object.install (index.js?bc58:14)
    at Object.use (runtime-core.esm-bundler.js?5c40:4016)
    at eval (main.js?56d7:169)
    at Module../src/main.js (app.js:3693)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at Object.1 (app.js:3718)
    at __webpack_require__ (app.js:849)
    at checkDeferredModules (app.js:46)
    at app.js:925
```

`Vue.component(addToHomescreen.name, addToHomescreen)`
`Uncaught TypeError: Cannot read property 'component' of undefined`

**Comment by matejicekme** [comment]
Hi there,

We're going to fix it by releasing a vue3 compatible version next week; sorry for the delay :).

**Comment by arsalan-nawadi** [comment]
> Hi there,
> 
> We're going to fix it by releasing a vue3 compatible version next week; sorry for the delay :).

any update on this?

**Comment by matejicekme** [comment]
Hi there !

Good news, plugin is now Vue3 compatible on v1.4.0 :). I've made the small fixes to made it working without destroying Vue 2 integration.

Feel free to post a new ticket if you find a bug.
